const API_BASE_URL = import.meta.env.VITE_API_URL || '';

export const API_ENDPOINTS = {
    erpBase: `${API_BASE_URL}/erp`,
    events: `${API_BASE_URL}/events`,
    announcements: `${API_BASE_URL}/announcements`,
    faculty: `${API_BASE_URL}/faculty`,
    gallery: `${API_BASE_URL}/gallery`,
    contacts: `${API_BASE_URL}/contacts`,
    login: `${API_BASE_URL}/auth/login`,
    adminMe: `${API_BASE_URL}/admin/me`,
    upload: `${API_BASE_URL}/upload`,
    images: `${API_BASE_URL}/images`,
    erpLogin: `${API_BASE_URL}/erp/auth/login`,
    erpMe: `${API_BASE_URL}/erp/me`,
    erpChangePassword: `${API_BASE_URL}/erp/me/change-password`,
    erpStudentDashboard: `${API_BASE_URL}/erp/student/dashboard`,
    erpTeacherDashboard: `${API_BASE_URL}/erp/teacher/dashboard`,
    erpGuardianDashboard: `${API_BASE_URL}/erp/guardian/dashboard`,
    erpGuardianChildDetails: (id) => `${API_BASE_URL}/erp/guardian/child/${id}/details`,
    erpNotifications: `${API_BASE_URL}/erp/notifications`,
    erpMessages: `${API_BASE_URL}/erp/messages`,
    erpSubstitutions: `${API_BASE_URL}/erp/substitutions/dashboard`,
    erpLeaves: `${API_BASE_URL}/erp/leaves`,
    erpMarks: `${API_BASE_URL}/erp/marks`,
    erpRazorpayOrder: `${API_BASE_URL}/erp/payments/razorpay/order`,
    erpRazorpayVerify: `${API_BASE_URL}/erp/payments/razorpay/verify`,
    erpReceipts: `${API_BASE_URL}/erp/receipts`,
    erpStudents: `${API_BASE_URL}/erp/students`,
    erpClassSections: `${API_BASE_URL}/erp/class-sections`,
    erpClassSectionStudents: (id) => `${API_BASE_URL}/erp/class-sections/${id}/students`,
    erpSubjects: `${API_BASE_URL}/erp/subjects`,
    erpTeacherAssignments: `${API_BASE_URL}/erp/teacher/assignments`,
    erpAttendanceBulk: `${API_BASE_URL}/erp/attendance/bulk`,
    erpAttendanceClass: `${API_BASE_URL}/erp/attendance/class`,
    erpExamSchedules: `${API_BASE_URL}/erp/exam-schedules`,
    erpTimetable: `${API_BASE_URL}/erp/timetable`,
    erpStudentAnalytics: `${API_BASE_URL}/erp/analytics/student`,
    erpClassAnalytics: `${API_BASE_URL}/erp/analytics/class`,
};

export default API_BASE_URL;
